# Generated by Django 3.0.3 on 2020-07-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_data',
            new_name='created_data',
        ),
    ]
